// <auto-generated />
namespace D.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class d003 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(d003));
        
        string IMigrationMetadata.Id
        {
            get { return "202002071251596_d003"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
